name: Bug Report
description: File a bug report
title: "🪲[Bug]: "
labels: ["bug", "triage"]
assignees:
  - srozemuller
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: correlationId
    attributes:
      label: correlationId
      description: Do you have a correlationId, if not in the browser, check the response header in your browers development tools under network. Find the call that is failing.
      placeholder: af14ea7d-f3d5-462f-8e4b-c1e089af693f  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell what did you expect to happen?
      placeholder: Plese tell what you see!
      value: "A bug happened!"
    validations:
      required: true
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What platform are you using?
      multiple: true
      options:
        - IntuneAssistant
        - Assignments Manager
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce?
      description: Is there a way to reproduce, what command did you use for example?
      placeholder: I did the following steps
      value: "This is what i did."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. For example the console log in your browser
      render: shell
