export const configurationTypes = [
    { value: "Update Ring Configuration", label: "Update Ring Configuration" },
    { value: "Group Policy Configuration", label: "Administrative Templates" },
    { value: "Windows Compliance Policy", label: "Windows Compliance Policy" },
    { value: "Ios Compliance Policy", label: "iOS Compliance Policy" },
    { value: "MacOs Compliance Policy", label: "macOS Compliance Policy" },
    { value: "Configuration Policy", label: "Configuration Policy" },
    { value: "Device Health Script", label: "Device Health Script" },
    { value: "Device Management Script", label: "Device Management Script" },
    { value: "Windows Autopilot Deployment Profile", label: "Windows Autopilot Deployment Profile" },
    { value: "Mobile App", label: "Mobile Application" },
    { value: "App Configuration Policy", label: "Application Configuration Policy" },
    { value: "Windows Managed App Protection", label: "Windows Managed Application Protection" },
    { value: "Ios Managed App Protection", label: "iOS Managed Application Protection" },
    { value: "Android Managed App Protection", label: "Android Managed Application Protection" },
    { value: "Windows Feature Update", label: "Windows Feature Update" },
    { value: "Windows Driver Update", label: "Windows Driver Update" },
    { value: "Windows Quality Update", label: "Windows Quality Update" },
    { value: "MacOs Shell Script", label: "macOS Shell Script" },
    { value: "Disk Encryption Policy", label: "Disk Encryption Policy" },
    { value: "Platform Scripts", label: "Platform Scripts" },
    { value: "Managed App Policy", label: "Managed Application Policy" },
    { value: "MacOs Device Features Configuration", label: "Mac OS Device Features Configuration" },
    { value: "MacOsEndpointProtectionConfiguration", label: "Mac OS Endpoint Protection Configuration" },
    { value: "DevicePlatformRestriction", label: "Device Platform Restriction" },
    { value: "DeviceLimitRestriction", label: "Device Limit Restriction" },
    { value: "MacOsCustomAttributes", label: "macOS Custom Attributes" },
    { value: "WindowsDefenderAdvancedThreatProtectionConfiguration", label: "Windows Defender ATP Configuration" },
    { value: "IosLobAppConfiguration", label: "iOS LineOfBusiness Application Configuration" },
    { value: "Win32LobApp", label: "Windows 32 LOB Application" },
    { value: "Win32StoreApp", label: "Windows 32 Store Application" },
    { value: "WingetApp", label: "Winget Application" },
    { value: "AndroidDeviceOwnerGeneralDeviceConfiguration", label: "Android Device Owner General Device Configuration" },
    { value: "Windows10CustomConfiguration", label: "Windows 10 Custom Configuration" },
    { value: "IosUpdateConfiguration", label: "iOS Update Configuration" },
    { value: "MacOsSoftwareUpdateConfiguration", label: "MacOS Software Update Configuration" },
    { value: "WindowsHealthMonitoringConfiguration", label: "Windows Health Monitoring Configuration" },
    { value: "DeviceEnrollmentPlatformRestrictionsConfiguration", label: "Device Enrollment Platform Restrictions Configuration" },
    { value: "DeviceEnrollmentLimitConfiguration", label: "Device Enrollment Limit Configuration" },
    { value: "IosCustomConfiguration", label: "iOS Custom Configuration" },
    { value: "IosGeneralConfiguration", label: "iOS General Configuration" },
    { value: "MacOsCustomConfiguration", label: "MacOS Custom Configuration" },
    { value: "WindowsIdentityProtectionConfiguration", label: "Windows Identity Protection Configuration" },
    { value: "MacOsExtensionsConfiguration", label: "MacOS Extensions Configuration" },
    { value: "WindowsKioskConfiguration", label: "Windows Kiosk Configuration" },
    { value: "AndroidWorkProfileGeneralDeviceConfiguration", label: "Android Work Profile General Device Configuration" },
    { value: "IosDeviceFeaturesConfiguration", label: "iOS Device Features Configuration" },
    { value: "IosGeneralDeviceConfiguration", label: "iOS General Device Configuration" },
    { value: "SharedPcConfiguration", label: "Shared PC Configuration" },
    { value: "IosDeviceFeatureConfiguration", label: "iOS Device Feature Configuration" },
    { value: "Endpoint detection and response", label: "Endpoint detection and response" },
    { value: "Windows Firewall", label: "Windows Firewall" },
    { value: "Windows Security Baseline", label: "Windows Security Baseline" },
    { value: "Microsoft Defender Antivirus", label: "Microsoft Defender Antivirus" },
    { value: "Microsoft Defender SmartScreen", label: "Microsoft Defender SmartScreen" },
    { value: "Attack Surface Reduction Rules", label: "Attack Surface Reduction Rules" },
    { value: "Elevation settings policy", label: "Elevation settings policy" },
    { value: "BitLocker", label: "BitLocker" },
    { value: "Attack Surface Reduction Rules (ConfigMgr)", label: "Attack Surface Reduction Rules (ConfigMgr)" },
    { value: "Security Baseline for Windows 10 and later", label: "Security Baseline for Windows 10 and later" },
    { value: "Security Baseline for Windows Server 2016 and later", label: "Security Baseline for Windows Server 2016 and later" },
    { value: "Security Baseline for Microsoft Edge", label: "Security Baseline for Microsoft Edge" },
    { value: "Local admin password solution (Windows LAPS)", label: "Local admin password solution (Windows LAPS)" },
    { value: "Windows Wifi Configuration", label: "Windows Wifi Configuration" },
    { value: "Windows Defender Exploit Guard", label: "Windows Defender Exploit Guard" },
    { value: "Windows Defender Application Control", label: "Windows Defender Application Control" },
    { value: "Windows Defender Application Guard", label: "Windows Defender Application Guard" },
    { value: "Windows Defender Credential Guard", label: "Windows Defender Credential Guard" },
    { value: "Windows Defender Device Guard", label: "Windows Defender Device Guard" },
    { value: "Windows Defender Firewall", label: "Windows Defender Firewall" },
    { value: "Windows Defender Antivirus Exclusions", label: "Windows Defender Antivirus Exclusions" },
    { value: "Windows Defender Antivirus Network Protection", label: "Windows Defender Antivirus Network Protection" },
    { value: "Windows Defender Antivirus Notifications", label: "Windows Defender Antivirus Notifications" },
    { value: "Windows Defender Antivirus Real-time Protection", label: "Windows Defender Antivirus Real-time Protection" },
    { value: "Windows Defender Antivirus Scan", label: "Windows Defender Antivirus Scan" },
    { value: "Windows Defender Antivirus Threat Protection", label: "Windows Defender Antivirus Threat Protection" },
    { value: "Windows Defender Antivirus Update", label: "Windows Defender Antivirus Update" },
    { value: "Windows Defender Antivirus Cloud Protection", label: "Windows Defender Antivirus Cloud Protection" },
    { value: "Windows Defender Antivirus Advanced Features", label: "Windows Defender Antivirus Advanced Features" },
    { value: "Windows Defender Antivirus Reporting", label: "Windows Defender Antivirus Reporting" },
    { value: "Windows Defender Antivirus Quarantine", label: "Windows Defender Antivirus Quarantine" },
    { value: "Windows Defender Antivirus Actions", label: "Windows Defender Antivirus Actions" },
    { value: "Windows Defender Antivirus Exclusions", label: "Windows Defender Antivirus Exclusions" },
    { value: "Windows Defender Antivirus Network Protection", label: "Windows Defender Antivirus Network Protection" },
    { value: "Windows Defender Antivirus Notifications", label: "Windows Defender Antivirus Notifications" },
    { value: "Windows Defender Antivirus Real-time Protection", label: "Windows Defender Antivirus Real-time Protection" },
    { value: "Windows Defender Antivirus Scan", label: "Windows Defender Antivirus Scan" },
    { value: "Windows 10 General Configuration", label: "Windows 10 General Configuration" },
    { value: "Elevation rules policy", label: "Elevation rules policy" },
    { value: "Windows Delivery Optimization Configuration", label: "Windows Delivery Optimization Configuration" },
    { value: "DeviceHealthScript", label: "Device Health Script" },
    { value: "WindowsDriverUpdate", label: "Windows Driver Update" },
    { value: "WindowsQualityUpdate", label: "Windows Quality Update" },
    { value: "DiskEncryptionPolicy", label: "Disk Encryption Policy" },
    { value: "WindowsFeatureUpdate", label: "Windows Feature Update" },
    { value: "MacOsShellScript", label: "MacOsShellScript" },
    { value: "PlatformScripts", label: "Platform Scripts" },
    { value: "ManagedAppPolicy", label: "Managed App Policy" },
    { value: "MacOsCustomAttributes", label: "MacOs Custom Attributes" },

];